# Gradio (ML Models interfaces)

## Installation

In [1]:
!pip install gradio
!pip install transformers

     |████████████████████████████████| 1.0MB 2.8MB/s 
     |████████████████████████████████| 215kB 18.1MB/s 
     |████████████████████████████████| 71kB 7.7MB/s 
     |████████████████████████████████| 2.6MB 16.7MB/s 
     |████████████████████████████████| 962kB 32.0MB/s 
     |████████████████████████████████| 890kB 2.9MB/s 
     |████████████████████████████████| 890kB 10.2MB/s 
     |████████████████████████████████| 3.0MB 21.1MB/s 
     |████████████████████████████████| 1.1MB 41.0MB/s 
  Created wheel for sacremoses: filename=sacremoses-0.0.43-cp36-none-any.whl size=893257 sha256=f566e4fd160b0962e800a8eab76a2c73ffe9b3a30f14c50299072f02b9fa2536
  Stored in directory: /root/.cache/pip/wheels/29/3c/fd/7ce5c3f0666dab31a50123635e6fb5e19ceb42ce38d4e58f45
Successfully built sacremoses


## Image Classification

In [2]:
import gradio as gr
import torch
import torchvision.models as models
from torchvision import transforms
import requests
from PIL import Image

alexnet = models.alexnet(pretrained=True).eval()
raw_labels = requests.get("https://gist.githubusercontent.com/yrevar/942d3a0ac09ec9e5eb3a/raw/238f720ff059c1f82f368259d1ca4ffa5dd8f9f5/imagenet1000_clsidx_to_labels.txt").text
labels = [i.split(',')[0] for i in list(eval(raw_labels).values())]

def inference(data):
    image = transforms.ToTensor()(Image.fromarray(data.astype('uint8'), 'RGB')).unsqueeze(0)
    prediction = torch.nn.functional.softmax(alexnet(image)[0], dim=0)
    dictionary = dict(zip(labels, map(float, prediction)))
    return dictionary

gr.Interface(fn=inference, 
             inputs=gr.inputs.Image(), 
             outputs=gr.outputs.Label(num_top_classes=5)).launch(share=True) #, debug=True Use in Colab

Downloading: "https://download.pytorch.org/models/alexnet-owt-4df8aa71.pth" to /root/.cache/torch/hub/checkpoints/alexnet-owt-4df8aa71.pth



Colab notebook detected. To show errors in colab notebook, set debug=True in launch()
This share link will expire in 6 hours. If you need a permanent link, email support@gradio.app
Running on External URL: https://12461.gradio.app
Interface loading below...


(<gradio.networking.serve_files_in_background.<locals>.HTTPServer at 0x7f86249b1f28>,
 'http://127.0.0.1:7860/',
 'https://12461.gradio.app')

## Text Generation

In [3]:
import tensorflow as tf
from transformers import TFGPT2LMHeadModel, GPT2Tokenizer

# Loading and setting up GPT2 Open AI Transformer Model
tokenizer = GPT2Tokenizer.from_pretrained("gpt2")
model = TFGPT2LMHeadModel.from_pretrained("gpt2", 
                                          pad_token_id=tokenizer.eos_token_id)

def generate_text(inp):
    # Encoding the starting point of the sentence we want to predict
    input_data = tokenizer.encode(inp, 
                                  return_tensors='tf')
    # Generating Output String
    output = model.generate(
        input_data, 
        do_sample=True, 
        max_length=50, 
        top_k=30
    )
    return tokenizer.decode(output[0], skip_special_tokens=True)

gr.Interface(generate_text,
             "textbox", 
             gr.outputs.Textbox()).launch(share=True) #, debug=True Use in Colab

All model checkpoint weights were used when initializing TFGPT2LMHeadModel.

All the weights of TFGPT2LMHeadModel were initialized from the model checkpoint at gpt2.
If your task is similar to the task the model of the checkpoint was trained on, you can already use TFGPT2LMHeadModel for predictions without further training.


Colab notebook detected. To show errors in colab notebook, set debug=True in launch()
This share link will expire in 6 hours. If you need a permanent link, email support@gradio.app
Running on External URL: https://11510.gradio.app
Interface loading below...


(<gradio.networking.serve_files_in_background.<locals>.HTTPServer at 0x7f85e53a67f0>,
 'http://127.0.0.1:7861/',
 'https://11510.gradio.app')

## Live General ML model prediction

In [5]:
# Preprocessing :
import pandas as pd
import numpy as np
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.metrics import classification_report,confusion_matrix
from itertools import product

# Classifiers
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from sklearn import svm
from sklearn import tree
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis
from sklearn.naive_bayes import GaussianNB
from sklearn.manifold import TSNE
from sklearn.decomposition import PCA

In [6]:
df = pd.read_csv("heart.csv")
df.head()

age  sex  cp  trestbps  chol  fbs  ...  exang  oldpeak  slope  ca  thal  target
0   63    1   3       145   233    1  ...      0      2.3      0   0     1       1
1   37    1   2       130   250    0  ...      0      3.5      0   0     2       1
2   41    0   1       130   204    0  ...      0      1.4      2   0     2       1
3   56    1   1       120   236    0  ...      0      0.8      2   0     2       1
4   57    0   0       120   354    0  ...      1      0.6      2   0     2       1

[5 rows x 14 columns]

In [7]:
df = df.drop(['cp','trestbps', 'fbs', 'thalach', 'exang', 'oldpeak', 'slope', 'ca', 'thal'], axis=1)
df.head()

age  sex  chol  restecg  target
0   63    1   233        0       1
1   37    1   250        1       1
2   41    0   204        0       1
3   56    1   236        1       1
4   57    0   354        1       1

In [8]:
df['age'].min(), df['age'].max()

(29, 77)

In [9]:
df['sex'].min(), df['sex'].max()

(0, 1)

In [10]:
df['chol'].min(), df['chol'].max()

(126, 564)

In [11]:
df['restecg'].min(), df['restecg'].max()

(0, 2)

In [12]:
X = df.drop(['target'], axis = 1).values
Y = df['target']

st = StandardScaler()
X = st.fit_transform(X)

X_Train, X_Test, Y_Train, Y_Test = train_test_split(X, Y, test_size = 0.30, random_state = 101)

In [13]:
trainedmodel = LogisticRegression().fit(X_Train,Y_Train)
predictions =trainedmodel.predict(X_Test)
print(confusion_matrix(Y_Test,predictions))
print(classification_report(Y_Test,predictions))

[[28 16]
 [13 34]]
              precision    recall  f1-score   support

           0       0.68      0.64      0.66        44
           1       0.68      0.72      0.70        47

    accuracy                           0.68        91
   macro avg       0.68      0.68      0.68        91
weighted avg       0.68      0.68      0.68        91



In [14]:
trainedforest = RandomForestClassifier(n_estimators=700).fit(X_Train,Y_Train)
predictionforest = trainedforest.predict(X_Test)
print(confusion_matrix(Y_Test,predictionforest))
print(classification_report(Y_Test,predictionforest))

[[25 19]
 [21 26]]
              precision    recall  f1-score   support

           0       0.54      0.57      0.56        44
           1       0.58      0.55      0.57        47

    accuracy                           0.56        91
   macro avg       0.56      0.56      0.56        91
weighted avg       0.56      0.56      0.56        91



In [15]:
trainedsvm = svm.LinearSVC().fit(X_Train, Y_Train)
predictionsvm = trainedsvm.predict(X_Test)
print(confusion_matrix(Y_Test,predictionsvm))
print(classification_report(Y_Test,predictionsvm))

[[28 16]
 [13 34]]
              precision    recall  f1-score   support

           0       0.68      0.64      0.66        44
           1       0.68      0.72      0.70        47

    accuracy                           0.68        91
   macro avg       0.68      0.68      0.68        91
weighted avg       0.68      0.68      0.68        91



In [16]:
trainedtree = tree.DecisionTreeClassifier().fit(X_Train, Y_Train)
predictionstree = trainedtree.predict(X_Test)
print(confusion_matrix(Y_Test,predictionstree))
print(classification_report(Y_Test,predictionstree))

[[28 16]
 [20 27]]
              precision    recall  f1-score   support

           0       0.58      0.64      0.61        44
           1       0.63      0.57      0.60        47

    accuracy                           0.60        91
   macro avg       0.61      0.61      0.60        91
weighted avg       0.61      0.60      0.60        91



In [17]:
trainedlda = LinearDiscriminantAnalysis().fit(X_Train, Y_Train)
predictionlda = trainedlda.predict(X_Test)
print(confusion_matrix(Y_Test,predictionlda))
print(classification_report(Y_Test,predictionlda))

[[28 16]
 [13 34]]
              precision    recall  f1-score   support

           0       0.68      0.64      0.66        44
           1       0.68      0.72      0.70        47

    accuracy                           0.68        91
   macro avg       0.68      0.68      0.68        91
weighted avg       0.68      0.68      0.68        91



In [18]:
trainednb = GaussianNB().fit(X_Train, Y_Train)
predictionnb = trainednb.predict(X_Test)
print(confusion_matrix(Y_Test,predictionnb))
print(classification_report(Y_Test,predictionnb))

[[31 13]
 [14 33]]
              precision    recall  f1-score   support

           0       0.69      0.70      0.70        44
           1       0.72      0.70      0.71        47

    accuracy                           0.70        91
   macro avg       0.70      0.70      0.70        91
weighted avg       0.70      0.70      0.70        91



In [28]:
def inference(age, sex, ch, cardio):
    s = 0 if sex=='female' else 1
    df = pd.DataFrame([[age, s, ch, cardio]], 
                      columns=['Age', 'Sex', 'Cholestoral (in mg/dl)', 
                               'Resting electrocardiographic results'])
    df = st.transform(df)
    pred = trainedmodel.predict_proba(df)[0]
    res = {'No Heart Desease': pred[0], 'Has Heart Desease': pred[1]}
    return res

sex = gr.inputs.Radio(['female', 'male'], label="Sex")
age = gr.inputs.Slider(minimum=1, maximum=100, default=22, label="Age")
ch = gr.inputs.Slider(minimum=120, maximum=560, default=200, label="Cholestoral (in mg/dl)")
cardio = gr.inputs.Radio([0, 1, 2], label="Resting electrocardiographic results")

gr.Interface(inference, [age, sex, ch, cardio], "label", live=True).launch(share=True) #, debug=True Use in Colab

Colab notebook detected. To show errors in colab notebook, set debug=True in launch()
This share link will expire in 6 hours. If you need a permanent link, email support@gradio.app
Running on External URL: https://42691.gradio.app
Interface loading below...


(<gradio.networking.serve_files_in_background.<locals>.HTTPServer at 0x7f85cffb8fd0>,
 'http://127.0.0.1:7869/',
 'https://42691.gradio.app')